name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install

      - name: Decode p12 file
        run: |
          echo "${{ secrets.CERT_P12 }}" | base64 --decode > cert.p12

      - name: Decode provisioning profile
        run: |
          echo "${{ secrets.PROVISION_PROFILE }}" | base64 --decode > profile.mobileprovision

      - name: Set up keychain and import certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import cert.p12 -k build.keychain -P "${{ secrets.CERT_PASSWORD }}" -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build IPA
        run: |
          xcodebuild -project ios/PipmPhotoApp.xcodeproj \
            -scheme PipmPhotoApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: PipmPhotoApp.ipa
          path: build/PipmPhotoApp.ipa
