name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    env:
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      P12_BASE64: ${{ secrets.CERT_P12 }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}

    steps:
      - uses: actions/checkout@v4

      - name: Decode .p12
        run: echo "$P12_BASE64" | base64 --decode > certificate.p12

      - name: Decode provisioning profile
        run: echo "$PROVISIONING_PROFILE" | base64 --decode > profile.mobileprovision

      - name: Setup keychain
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Setup provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build app
        run: |
          xcodebuild -workspace ios/PIPMVisiteurs.xcworkspace \
            -scheme PIPMVisiteurs \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ios/build/PIPMVisiteurs.xcarchive \
            DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
            archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/PIPMVisiteurs.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath ios/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: PIPMPhotoVisite.ipa
          path: ios/build/*.ipa
