name: Build IPA

on:
  push:
    branches:
      - main

env:
  DEVELOPMENT_TEAM: 23NM8VWVGR
  P12_BASE64: ${{ secrets.P12_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install
        cd ios && pod install

    - name: Decode and import certificate
      run: |
        echo "$P12_BASE64" | base64 -d > certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import certificate.p12 -k build.keychain -P "$P12_PASSWORD" -A -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

    - name: Build IPA
      run: |
        xcodebuild -workspace ios/PIPMVisiteurs.xcworkspace \
          -scheme PIPMVisiteurs \
          -configuration Release \
          -sdk iphoneos \
          -archivePath ios/build/PIPMVisiteurs.xcarchive \
          DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
          archive

        xcodebuild -exportArchive \
          -archivePath ios/build/PIPMVisiteurs.xcarchive \
          -exportOptionsPlist ios/exportOptions.plist \
          -exportPath ios/build

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: PIPMVisiteurs.ipa
        path: ios/build/*.ipa
