name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Decode cert.p12
        run: |
          echo "${{ secrets.P12_BASE64 }}" | base64 --decode > cert.p12

      - name: Decode provisioning profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > profile.mobileprovision

      - name: Set up keychain and import certificate
        run:
             security create-keychain -p "temp_pass" build.keychain
             security default-keychain -s build.keychain
            security unlock-keychain -p "temp_pass" build.keychain
            security import cert.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
            mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
            cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/


      - name: Install dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        run: |
          xcodebuild -workspace ios/PipmPhotoApp.xcworkspace \
            -scheme PipmPhotoApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive \
            -allowProvisioningUpdates \
            clean archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive \
            -exportOptionsPlist ios/build/exportOptions.plist \
            -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: PipmPhotoApp.ipa
          path: build/PipmPhotoApp.ipa
