name: Build iOS

on:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install CocoaPods
        run: |
          cd ios
          pod install

      - name: Decode certificates
        env:
          P12_BASE64: ${{ secrets.CERT_P12 }}
          P12_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
        run: |
          mkdir -p ~/certs
          echo "$P12_BASE64" | base64 --decode > ~/certs/cert.p12
          echo "$PROFILE_BASE64" | base64 --decode > ~/certs/profile.mobileprovision

      - name: Install certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ~/certs/cert.p12 -P "$P12_PASSWORD" -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build .ipa
        run: |
          xcodebuild -workspace ios/PipmPhotoApp.xcworkspace \
            -scheme PipmPhotoApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive \
            -allowProvisioningUpdates \
            archive

          xcodebuild -exportArchive \
            -archivePath $PWD/build/PipmPhotoApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath $PWD/build/ipa

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v4
        with:
          name: PipmPhotoApp
          path: build/ipa
