name: Build iOS App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build iOS with xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Decode .p12 certificate
        run: |
          echo "${{ secrets.CERT_P12 }}" | base64 --decode > cert.p12

      - name: Decode provisioning profile
        run: |
          echo "${{ secrets.PROVISIONING_PROFILE }}" | base64 --decode > profile.mobileprovision

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          UUID=$(grep -a -E -o '[-A-Z0-9]{36}' profile.mobileprovision | head -1)
          cp profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision

      - name: Install certificate
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import cert.p12 -k build.keychain -P "${{ secrets.P12_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build iOS app
        run: |
          xcodebuild \
            -project ios/PipmPhotoApp.xcodeproj \
            -scheme PipmPhotoApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath ios/build/PipmPhotoApp.xcarchive \
            archive \
            DEVELOPMENT_TEAM=${{ secrets.DEVELOPMENT_TEAM }}

      - name: Export .ipa
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath ios/build/PipmPhotoApp.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath ios/build \
            -allowProvisioningUpdates
            
      - name: Upload .ipa file
        uses: actions/upload-artifact@v4
        with:
          name: PipmPhotoApp
          path: ios/build/*.ipa
